### PR TITLE
Fix/remove admin updatedb

### PR DESCRIPTION
**Pull request by whatnick**
- Completely remove unused updatedb
- Roll-back update creation-dt a little bit. Can't really get rid of it until there is a scheduled job framework in production.

### CODE REVIEW

**Comment by tom-butler** [comment]
I understand we don't use it, but this is a public helm chart, shouldn't we keep the cron jobs for users that don't have our job framework?

**Comment by whatnick** [comment]
How would we know if there are other users of this chart ? the update-db and update-creation-dt are copy pasted duplicates and need only one.

**Comment by pindge** [comment]
Make a note, from `version: x.x.x` onwards, `updateDB` is no longer available, please config locally. or something

**Comment by woodcockr** [comment]
> How would we know if there are other users of this chart ? the update-db and update-creation-dt are copy pasted duplicates and need only one.

They will complain and curse you for making the opendatacube community repository into the DEA production repository and thus forcing specific deployment and change management onto them ;-).

It is best to assume it is in use and a) use a deprecation process and/or b) change a major version number on release, tag things and generally do everything in your power to not break existing deployments without notification and the opportunity to pin against a version for when the "others" as ready to update.

**Comment by pindge** [comment]
I prefer once in a while do a tagged release when the chart is confirmed to be stable and has major changes.

**Pull request merged**
